# Generated by Django 4.1.3 on 2022-11-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='default_branch',
            field=models.CharField(default='main', max_length=100),
        ),
    ]
