# Generated by Django 4.1.3 on 2022-11-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_default_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='path',
            field=models.FileField(blank=True, null=True, upload_to='projects/paths'),
        ),
    ]
